# This is a basic workflow to help you get started with Actions

name: Crawler

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "* */6 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests
      - name: Crawling
        run: |
          python crawler.py
      - name: Commit files
        run: |
          git config --local user.email "bot@4.bytes"
          git config --local user.name "4bytes[bot]"
          git commit -m "Automatic crawling" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
